import { type CalibreMetadata } from './CalibreMetadata.ts'

export const refactoringDatabases = () => {
  return `Title               : Refactoring Databases: Evolutionary Database Design
Author(s)           : Scott W. Ambler & Pramod J. Sadalage
Publisher           : Addison Wesley
Tags                : Computers, General, Database Administration & Management, System Administration, Storage & Retrieval, Programming, Object Oriented, Software Development & Engineering, Data Science, Data Modeling & Design
Languages           : eng
Rating              : 2
Published           : 2006-03-03T00:00:00+00:00
Identifiers         : google:uj6emAEACAAJ, isbn:9780321774514, amazon:0321774515
Comments            : <p>Refactoring has proven its value in a wide range of development projects–helping software professionals improve system designs, maintainability, extensibility, and performance. Now, for the first time, leading agile methodologist Scott Ambler and renowned consultant Pramodkumar Sadalage introduce powerful refactoring techniques specifically designed for database systems.</p>
<p>Ambler and Sadalage demonstrate how small changes to table structures, data, stored procedures, and triggers can significantly enhance virtually any database design–without changing semantics. You’ll learn how to evolve database schemas in step with source code–and become far more effective in projects relying on iterative, agile methodologies.</p>
<p>This comprehensive guide and reference helps you overcome the practical obstacles to refactoring real-world databases by covering every fundamental concept underlying database refactoring. Using start-to-finish examples, the authors walk you through refactoring simple standalone database applications as well as sophisticated multi-application scenarios. You’ll master every task involved in refactoring database schemas, and discover best practices for deploying refactorings in even the most complex production environments. </p>
<p>The second half of this book systematically covers five major categories of database refactorings. You’ll learn how to use refactoring to enhance database structure, data quality, and referential integrity; and how to refactor both architectures and methods. This book provides an extensive set of examples built with Oracle and Java and easily adaptable for other languages, such as C#, C++, or VB.NET, and other databases, such as DB2, SQL Server, MySQL, and Sybase.</p>
<p>Using this book’s techniques and examples, you can reduce waste, rework, risk, and cost–and build database systems capable of evolving smoothly, far into the future. </p><h3>From the Back Cover</h3>
<p>Refactoring has proven its value in a wide range of development projects―helping software professionals improve system designs, maintainability, extensibility, and performance. Now, for the first time, leading agile methodologist Scott Ambler and renowned consultant Pramodkumar Sadalage introduce powerful refactoring techniques specifically designed for database systems.</p>
<p>Ambler and Sadalage demonstrate how small changes to table structures, data, stored procedures, and triggers can significantly enhance virtually any database design―without changing semantics. You’ll learn how to evolve database schemas in step with source code―and become far more effective in projects relying on iterative, agile methodologies.</p>
<p>This comprehensive guide and reference helps you overcome the practical obstacles to refactoring real-world databases by covering every fundamental concept underlying database refactoring. Using start-to-finish examples, the authors walk you through refactoring simple standalone database applications as well as sophisticated multi-application scenarios. You’ll master every task involved in refactoring database schemas, and discover best practices for deploying refactorings in even the most complex production environments. </p>
<p>The second half of this book systematically covers five major categories of database refactorings. You’ll learn how to use refactoring to enhance database structure, data quality, and referential integrity; and how to refactor both architectures and methods. This book provides an extensive set of examples built with Oracle and Java and easily adaptable for other languages, such as C#, C++, or VB.NET, and other databases, such as DB2, SQL Server, MySQL, and Sybase.</p>
<p>Using this book’s techniques and examples, you can reduce waste, rework, risk, and cost―and build database systems capable of evolving smoothly, far into the future. </p>
<h3>About the Author</h3>
<p><strong>Scott W. Ambler</strong> is a software process improvement (SPI) consultant living just north of Toronto. He is founder and practice leader of the Agile Modeling (AM) (www.agilemodeling.com), Agile Data (AD) (www.agiledata.org), Enterprise Unified Process (EUP) (www.enterpriseunifiedprocess.com), and Agile Unified Process (AUP) (www.ambysoft.com/unifiedprocess) methodologies. Scott is the (co-)author of several books, including <em>Agile Modeling</em> (John Wiley &amp; Sons, 2002), <em>Agile Database Techniques</em> (John Wiley &amp; Sons, 2003), <em>The Object</em> <em>Primer, Third Edition</em> (Cambridge University Press, 2004), <em>The Enterprise Unified</em> <em>Process</em> (Prentice Hall, 2005), and <em>The Elements of UML 2.0 Style</em> (Cambridge University Press, 2005). Scott is a contributing editor with <em>Software Development</em> magazine (www.sdmagazine.com) and has spoken and keynoted at a wide variety of international conferences, including Software Development, UML World, Object Expo, Java Expo, and Application Development. Scott graduated from the University of Toronto with a Master of Information Science. In his spare time Scott studies the Goju Ryu and Kobudo styles of karate.</p>
<p><strong>Pramod J. Sadalage</strong> is a consultant for ThoughtWorks, an enterprise application development and integration company. He first pioneered the practices and processes of evolutionary database design and database refactoring in 1999 while working on a large J2EE application using the Extreme Programming (XP) methodology. Since then, Pramod has applied the practices and processes to many projects. Pramod writes and speaks about database administration on evolutionary projects, the adoption of evolutionary processes with regard to databases, and evolutionary practices’ impact upon database administration, in order to make it easy for everyone to use evolutionary design in regards to databases. When he is not working, you can find him spending time with his wife and daughter and trying to improve his running.</p>` as CalibreMetadata
}

export const superNesAVisual = () => {
  return `Title               : Super Nes-Super Famicom a Visual
Author(s)           : Bitmap Books
Publisher           : Bitmap Books
Languages           : eng
Rating              : 2.5
Published           : 2017-05-15T16:15:06.838290+00:00
Identifiers         : google:ax9rtAEACAAJ, isbn:9780995658622, amazon:0995658625
Comments            : <p>SNES/Super a visual compendium It would be a massive understatement to say that the Super Nintendo had a formidable act to follow when it arrived at the dawn of the 1990s. Nintendo's previous console the NES (or Famicom as it was known in its native Japan) enjoyed seven years of almost unrivalled dominance following its initial launch in Japan in 1983 and had almost single-handedly rehabilitated the home video game market, turning Nintendo into a household name across the globe. Focussing on the Super Famicom in Japan and the SNES across North America and Europe, SNES/Super a visual compendium offers a visual snapshot of the best games, developers, box art and product design from across these territories. As the name suggests, the book is mainly visual; it won't be a super-detailed insight into the SNES/Super Famicom, but more a visual companion designed to stir up excitement and nostalgia for this fantastic machine and its legacy of classic games. The book measures 170mm x 230mm and is printed lithographically to the highest standards. This ensures that colours in the book are really vibrant and pages have a high-quality, luxurious feel to them. As standard, all visual compendiums now come with a spot varnished cover and a spot varnished protective dust jacket. The binding is 'thread sewn' which means that the book can lie flat so the imagery can be fully enjoyed. The binding does not use glue which can crack over time and result in loose pages. Thread sewn binding is the best available. SNES/Super a visual compendium comes as a hardback edition and 500+ pages long. It also comes with four Super Famicom coloured bookmark ribbons and a 3mm protective board slipcase which has a lenticular fascia and is shrink-wrapped. Book 536 pages, 170mm x 230mm, Hardback,3mm protective board slipcase with lenticular fascia, Lithographic print, Sewn binding, Spot varnish cover, Spot varnish dust jacket</p>` as CalibreMetadata
}

export const metadataWithMultipleAuthors = refactoringDatabases
export const metadataWithTags = refactoringDatabases
export const metadataWithoutTags = superNesAVisual
